# This is an example configfile
datafile = "data/example_file.txt"
# In this case there is no maskfile necessary, so we have commented it out.
# maskfile = "data/example_mask.fits"
epochs = 5
network_name = "n_layer_resnet"
export_to_csv = true

[network_settings]
last_layer = "layer4"

[data_settings]
remove_unrelated_data = true
median_fill = false
stacksize = 3

[byol_settings]
representation_size = 128
projection_size = 64
projection_hidden_size = 256
use_momentum = true
