# This is an example configfile
datafile = "data/example_file.txt"
# In this case there is no maskfile necessary, so we have commented it out.
# maskfile = "data/example_mask.fits"
epochs = 5
last_layer = "layer4"
